---
username: ben
hostname: BenLaptop
startChargeThreshold: 40
endChargeThreshold: 70
wifiSSID: nameOfWPA3SSID
# From https://extensions.gnome.org/
gnome_extension_ids:
  - 5004
  - 19
  - 2
  - 906
  - 3733
  - 615
  - 4798
flatpaks:
  - org.mozilla.firefox
  - com.spotify.Client
  - com.visualstudio.code
  - org.remmina.Remmina
  - org.videolan.VLC
  - com.bitwarden.desktop
  - org.signal.Signal
  - org.chromium.Chromium
  - org.gnome.Firmware
  - ca.desrt.dconf-editor
  - org.fedoraproject.MediaWriter
  - org.keepassxc.KeePassXC
  - org.qbittorrent.qBittorrent
  - org.wireshark.Wireshark
  - com.mattjakeman.ExtensionManager
  - org.freedesktop.Platform.ffmpeg-full
  - org.gtk.Gtk3theme.Arc
ostreeInstallRpms:
  - zsh
  - solaar
  - virt-manager
  - qemu-kvm
  - tmux
ostreeUninstallRpms:
  - firefox
toolboxInstallRpms:
  - zsh
  - arc-theme
  - gnome-tweak-tool
  - gnome-shell
dconfSettings:
  - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock/background-opacity
    value: "0.8"
  - key: /org/gnome/shell/extensions/dash-to-dock/click-action
    value: "'previews'"
  - key: /org/gnome/shell/extensions/dash-to-dock/scroll-action
    value: "'cycle-windows'"
  - key: /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size
    value: "32"
  - key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock/dock-position
    value: "'LEFT'"
  - key: /org/gnome/shell/extensions/dash-to-dock/extend-height
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock/multi-monitor
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock/transparency-mode
    value: "'DYNAMIC'"
  - key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock/show-trash
    value: "false"
  - key: /org/gnome/shell/extensions/dash-to-dock/isolate-monitors
    value: "true"
  - key: /org/gnome/shell/extensions/user-theme/name
    value: "'Arc-Dark'"
  - key: /org/gnome/shell/enabled-extensions
    value: "['background-logo@fedorahosted.org', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-dock@micxgx.gmail.com']"
  - key: /org/gnome/shell/favorite-apps
    value: "['org.mozilla.firefox.desktop', 'org.gnome.Nautilus.desktop']"
  - key: /org/gnome/desktop/interface/icon-theme
    value: "'Tela-dark'"
  - key: /org/gnome/desktop/interface/gtk-theme
    value: "'Arc-Dark'"
  - key: /org/gnome/desktop/interface/clock-show-weekday
    value: "true"
  - key: /org/gnome/desktop/interface/show-battery-percentage
    value: "true"
  - key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "false"
  - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
    value: "true"
  - key: /org/gnome/settings-daemon/plugins/power/idle-dim
    value: "true"
  - key: /org/gnome/desktop/notifications/show-in-lock-screen
    value: "false"
  - key: /org/gnome/desktop/screensaver/lock-delay
    value: "30"
  - key: /org/gnome/desktop/privacy/remove-old-temp-files
    value: "true"
  - key: /org/gnome/desktop/privacy/remove-old-trash-files
    value: "true"
  - key: /org/gnome/desktop/datetime/automatic-timezone
    value: "true"
  - key: /org/gnome/shell/weather/automatic-location
    value: "true"
  - key: /org/gnome/desktop/interface/text-scaling-factor
    value: "1"
  - key: /org/gnome/desktop/interface/font-antialiasing
    value: "'rgba'"
homeDirectories:
  - repos
  - AppImage
  - .themes
