---
username: ben
hostname: ben-t14s
startChargeThreshold: 40
endChargeThreshold: 70
wifiSSID: nameOfWPA3SSID
# From https://extensions.gnome.org/
gnome_extension_ids:
  - 5004
  - 19
  - 2
  - 906
  - 3733
  - 615
  - 4798
flatpaks:
  - org.mozilla.firefox
  - com.spotify.Client
  - com.visualstudio.code
  - org.remmina.Remmina
  - org.videolan.VLC
  - com.bitwarden.desktop
  - org.signal.Signal
  - org.chromium.Chromium
  - org.gnome.Firmware
  - ca.desrt.dconf-editor
  - org.fedoraproject.MediaWriter
  - org.keepassxc.KeePassXC
  - org.qbittorrent.qBittorrent
  - org.wireshark.Wireshark
  - com.mattjakeman.ExtensionManager
  - org.freedesktop.Platform.ffmpeg-full
  - org.gtk.Gtk3theme.Arc
  - org.standardnotes.standardnotes
ostreeInstallRpms:
  - zsh
  - solaar
  - virt-manager
  - qemu-kvm
  - tmux
ostreeUninstallRpms:
  - firefox
toolboxInstallRpms:
  - zsh
  - arc-theme
  - gnome-tweak-tool
  - gnome-shell
dconfSettings:
  - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"
  - key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
    value: "21"
  - key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
    value: "7"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/background-opacity
    value: "0.8"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop-pop/click-action
    value: "'previews'"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop-pop/scroll-action
    value: "'cycle-windows'"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/dash-max-icon-size
    value: "32"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/dock-alignment
    value: "'CENTRE'"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/dock-fixed
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/dock-position
    value: "'LEFT'"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/extend-height
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/show-trash
    value: "false"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/isolate-monitors
    value: "true"
  - key: /org/gnome/shell/extensions/dash-to-dock-pop/scroll-action
    value: "'cycle-windows'"
  - key: /org/gnome/shell/extensions/user-theme/name
    value: "'Arc-Dark'"
  - key: /org/gnome/shell/disabled-extensions
    value: "['sound-output-device-chooser@kgshank.net']"
  - key: /org/gnome/shell/enabled-extensions
    value: "['background-logo@fedorahosted.org', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-dock@micxgx.gmail.com', 'Move_Clock@rmy.pobox.com', 'appindicatorsupport@rgcjonas.gmail.com', 'thinkpad-battery-threshold@marcosdalvarez.org', 'wintile@nowsci.com', 'tiling-assistant@leleat-on-github', 'dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com']"
  - key: /org/gnome/shell/favorite-apps
    value: "['org.mozilla.firefox.desktop', 'org.gnome.Terminal.desktop']"
  - key: /org/gnome/shell/keybindings/show-screenshot-ui
    value: "['<Shift><Super>s']"
  - key: /org/gnome/shell/overrides/edge-tiling
    value: "false"
  - key: /org/gnome/shell/extensions/thinkpad-battery-threshold/start-bat0
    value: "{{ startChargeThreshold }}"
  - key: /org/gnome/shell/extensions/thinkpad-battery-threshold/stop-bat0
    value: "{{ endChargeThreshold }}"
  - key: /org/gnome/shell/extensions/sound-output-device-chooser/hide-on-single-device
    value: "true"
  - key: /org/gnome/shell/extensions/sound-output-device-chooser/integrate-with-slider
    value: "true"
  - key: /org/gnome/shell/extensions/sound-output-device-chooser/show-profiles
    value: "true"
  - key: /org/gnome/desktop/interface/icon-theme
    value: "'Tela'"
  - key: /org/gnome/desktop/interface/gtk-theme
    value: "'Arc'"
  - key: /org/gnome/desktop/interface/clock-show-weekday
    value: "true"
  - key: /org/gnome/desktop/interface/show-battery-percentage
    value: "true"
  - key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "false"
  - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
    value: "true"
  - key: /org/gnome/settings-daemon/plugins/power/idle-dim
    value: "true"
  - key: /org/gnome/desktop/notifications/show-in-lock-screen
    value: "false"
  - key: /org/gnome/desktop/screensaver/lock-delay
    value: "30"
  - key: /org/gnome/desktop/privacy/remove-old-temp-files
    value: "true"
  - key: /org/gnome/desktop/privacy/remove-old-trash-files
    value: "true"
  - key: /org/gnome/desktop/datetime/automatic-timezone
    value: "true"
  - key: /org/gnome/shell/weather/automatic-location
    value: "true"
  - key: /org/gnome/desktop/remote-desktop/rdp/screen-share-mode
    value: "'extend'"
  - key: /org/gnome/desktop/interface/text-scaling-factor
    value: "1"
  - key: /org/gnome/desktop/interface/font-antialiasing
    value: "'rgba'"
homeDirectories:
  - repos
  - AppImage
  - .themes
