---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Install overlay packages
      community.general.rpm_ostree_pkg:
        name: "{{ item }}"
        state: present
      loop: "{{ ostreeInstallRpms }}"

    - name: Remove overlay packages
      community.general.rpm_ostree_pkg:
        name: "{{ item }}"
        state: absent
      loop: "{{ ostreeUninstallRpms }}"

    - name: Update Silverblue
      ansible.builtin.command: rpm-ostree upgrade

    - name: Create Toolbox
      ansible.builtin.command: toolbox create -y
      register: toolboxCreate
      failed_when:
        - toolboxCreate.rc > 0
        - '"already exists" not in toolboxCreate.stderr'

    - name: Install Toolbox packages
      ansible.builtin.command: "toolbox run sudo dnf install -y {{ toolboxInstallRpms | join(' ') }}"

    - name: Change default shell to zsh
      ansible.builtin.command: usermod --shell /bin/zsh $USER
      become: yes

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    
    - name: Install flatpak packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
      loop: "{{ flatpaks }}"

    - name: Create directories
      ansible.builtin.file:
        path: "~/{{ item }}"
        state: directory
      loop: "{{ homeDirectories }}"
    
    - name: Pull Tela icons
      ansible.builtin.git:
        repo: 'https://github.com/vinceliuice/Tela-icon-theme.git'
        dest: ~/repos/Tela-icon-theme
        update: no

    - name: Install Tela icons
      ansible.builtin.command: ./install.sh
      args:
        chdir: ~/repos/Tela-icon-theme

    - name: Include GNOME Extensions role
      include_role:
        name: jaredhocutt.gnome_extensions

    - name: Change dconf settings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop: "{{ dconfSettings }}"

    - name: Set charge start threshold
      ansible.builtin.copy:
        dest: /sys/class/power_supply/BAT0/charge_control_start_threshold
        content: "{{ startChargeThreshold }}"
      become: yes

    - name: Set charge end threshold
      ansible.builtin.copy:
        dest: /sys/class/power_supply/BAT0/charge_control_end_threshold
        content: "{{ endChargeThreshold }}"
      become: yes

    - name: Enable wifi MAC randomisation
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/mac-randomization.conf
        content: |
          [device-mac-randomization]
          wifi.scan-rand-mac-address=yes
          [connection-mac-randomization]
          #ethernet.assigned-mac-address=random
          wifi.assigned-mac-address=random
      become: yes

    - name: Modify wifi connection settings
      community.general.nmcli:
        type: wifi
        conn_name: "{{ networkManagerConnectionName }}"
        wifi:
          assigned-mac-address: preserve
        wifi_sec:
          auth-alg: ""
          key-mgmt: sae
          pmf: 3

    - name: Restart NetworkManager service
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

    - name: Add shortcut to Gnome Tweaks
      ansible.builtin.copy:
        dest: ~/.local/share/applications/GnomeTweaks.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Gnome Tweaks (toolbox)
          Exec=/bin/toolbox run gnome-tweaks
          Icon=org.gnome.Settings
          Terminal=false
