---
# https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
roles:
  - name: jaredhocutt.gnome_extensions

collections:
  - name: community.general
